<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Данные с виджета Отклонение объема потерь(Блок Балансы)</name>
   <tag></tag>
   <elementGuidId>7e74dbba-2cfa-4561-bea4-e22b65553b71</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[22]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.highcharts-root</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>9aadab51-f00f-4927-882e-2afbe1e4cf1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>version</name>
      <type>Main</type>
      <value>1.1</value>
      <webElementGuid>dac8bd8a-fc5c-4150-8829-f3552ecfde6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>highcharts-root</value>
      <webElementGuid>f00107b6-b772-4c52-8416-f58432e62202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>b8908313-0fd2-42f8-8ee8-c70e4e3fbc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>890</value>
      <webElementGuid>a0464688-859b-454a-b1b2-eb13be56104d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>420</value>
      <webElementGuid>d9e36ead-5caf-41e2-8234-eac51e5b6aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 890 420</value>
      <webElementGuid>528f4e39-2f1c-40f6-9d0b-80c33dad092e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Created with Highcharts 9.0.1153 017​153 0172022 год0 25 50 75 100 125 150 175 2022: 153 017</value>
      <webElementGuid>bf94b503-0c68-4f57-ae6a-8b9406295833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-q0em2wy-170&quot;)/svg[@class=&quot;highcharts-root&quot;]</value>
      <webElementGuid>39078b86-18a5-4530-996a-42d6ad7958bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Объем потерь по АО «Тываэнерго» за 2022 год'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>9c673a24-6ca5-48e3-8c63-8aa2dead66df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[17]/following::*[name()='svg'][1]</value>
      <webElementGuid>9c5bd46f-de9a-4a5b-86ff-0a6b237f0f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//svg[(text() = 'Created with Highcharts 9.0.1153 017​153 0172022 год0 25 50 75 100 125 150 175 2022: 153 017' or . = 'Created with Highcharts 9.0.1153 017​153 0172022 год0 25 50 75 100 125 150 175 2022: 153 017')]</value>
      <webElementGuid>e6ea364c-27db-4866-bc08-1b90ea39d2b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
