<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_-close</name>
   <tag></tag>
   <elementGuidId>cee98398-3383-4bb5-a317-c90d470de608</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-times.rb-filter-header-close</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='b26ef35cc026401dbcf8a1340eff9601']/div/div/i[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>19b089bd-dc8d-45cc-a77c-a2d58347427f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-times rb-filter-header-close</value>
      <webElementGuid>9d852798-a8f2-4c5f-b967-fb759eb9e12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Очистить все выбранные значения</value>
      <webElementGuid>de5bf600-0d79-4c9a-befc-653e9d581002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;b26ef35cc026401dbcf8a1340eff9601&quot;)/div[@class=&quot;rb-filter-container not-selectable rb-filter-multi-selection&quot;]/div[@class=&quot;rb-filter-header-container&quot;]/i[@class=&quot;fa fa-times rb-filter-header-close&quot;]</value>
      <webElementGuid>4f337c2d-2ac7-4a9c-999d-e297c5e18b56</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='b26ef35cc026401dbcf8a1340eff9601']/div/div/i[2]</value>
      <webElementGuid>312aa33c-edfe-4ea4-88db-5e18b52d3453</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i[2]</value>
      <webElementGuid>8e93ff0f-88e1-4811-94f8-92f3f69e19d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@title = 'Очистить все выбранные значения']</value>
      <webElementGuid>2ca65701-9451-48b0-a1c9-8d3de37e1138</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
