<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ПАО Россети</name>
   <tag></tag>
   <elementGuidId>a8e94d47-2b69-435c-9d03-630caa4b2ae3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[13]/div[2]/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#5195de9ab2cf459e8c675d3617047a56 > div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1b336210-52f2-45dc-b1a4-7d9260c97043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;5195de9ab2cf459e8c675d3617047a56&quot;)/div[1]</value>
      <webElementGuid>ce405dea-350c-4293-be24-d3f170627838</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='5195de9ab2cf459e8c675d3617047a56']/div</value>
      <webElementGuid>c68dc775-e08f-4db4-9699-a70224cf47c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div[2]/div/div</value>
      <webElementGuid>bdfd0e36-a0d3-45d5-a7c9-20120075e391</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
