<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Уровень потерь Россети Северный Кавказ(ГК)</name>
   <tag></tag>
   <elementGuidId>1fda3418-b12d-4920-b595-b78d1c863348</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[36]/div[2]/div/div/div/div/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#highcharts-qfvlkfr-138 > div.highcharts-data-labels.highcharts-series-0.highcharts-column-series.highcharts-tracker > div.highcharts-label.highcharts-data-label.highcharts-data-label-color-undefined.highcharts-tracker.highcharts-drilldown-data-label > span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>1eb1f93f-705f-49fc-a657-030617c629bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-z-index</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>76b55a9a-1c5f-49b8-a5c5-d371071e5d45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25.53 </value>
      <webElementGuid>5c8c3d43-67ad-4412-9c87-c70868008e72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;highcharts-qfvlkfr-138&quot;)/div[@class=&quot;highcharts-data-labels highcharts-series-0 highcharts-column-series highcharts-tracker&quot;]/div[@class=&quot;highcharts-label highcharts-data-label highcharts-data-label-color-undefined highcharts-tracker highcharts-drilldown-data-label&quot;]/span[1]</value>
      <webElementGuid>54a622a5-54b6-4d8f-8274-c6d851c1b159</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='highcharts-qfvlkfr-138']/div/div/span</value>
      <webElementGuid>3ba97942-47dd-4f99-9c43-8a6d605a803f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Факт'])[6]/following::span[1]</value>
      <webElementGuid>288c97ec-47f6-4a21-8a7e-7c52afa13a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created with Highcharts 9.0.1'])[2]/following::span[1]</value>
      <webElementGuid>c663e185-f70b-445a-b4ba-fa5d7e0dd524</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[19]/preceding::span[1]</value>
      <webElementGuid>4c8f129f-b039-438d-b7db-c1ebabf7eee3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Отклонения, %'])[1]/preceding::span[1]</value>
      <webElementGuid>25f208ac-43c7-4b2c-8a0c-c78c345e1ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='25.53']/parent::*</value>
      <webElementGuid>b6e11efa-d2cf-4a3f-8c37-aedc9f9a943b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[36]/div[2]/div/div/div/div/span</value>
      <webElementGuid>04856b25-6c10-4549-9550-9b6dec8091b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '25.53 ' or . = '25.53 ')]</value>
      <webElementGuid>259ec382-887b-4598-b7d3-865e8559fce8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
