<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>фильтр составляющая Баланса</name>
   <tag></tag>
   <elementGuidId>3f28af3d-81ea-4a1b-a906-37aa7894784f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='3892f5916a87476580efdda2efa5afa5']/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#e4cba663ee1d4c50a7f08c50ff94cba9 > div.rb-filter-container.not-selectable.rb-filter-multi-selection > div.rb-filter-header-container > div.rb-filter-header-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4a2d9f91-a702-43da-8453-025719fc5138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rb-filter-header-text</value>
      <webElementGuid>daa1460b-9c28-4042-a3a6-b10c82af4a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Итого</value>
      <webElementGuid>b6f7fc81-0d8d-48c3-803f-a40ff8b62c67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;e4cba663ee1d4c50a7f08c50ff94cba9&quot;)/div[@class=&quot;rb-filter-container not-selectable rb-filter-multi-selection&quot;]/div[@class=&quot;rb-filter-header-container&quot;]/div[@class=&quot;rb-filter-header-text&quot;]</value>
      <webElementGuid>67c9478e-aa68-427e-b485-335f921b201a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='e4cba663ee1d4c50a7f08c50ff94cba9']/div/div/div</value>
      <webElementGuid>afe7fabe-4980-4938-9bc3-d201bdc0826b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Составляющая баланса'])[1]/following::div[5]</value>
      <webElementGuid>e060d689-d652-4c1f-b334-d1ca899654b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='В начало'])[8]/following::div[11]</value>
      <webElementGuid>70747213-35df-41be-893a-e581ec96d8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Выбранные значения'])[8]/preceding::div[1]</value>
      <webElementGuid>08047957-5bce-415b-aada-da162b7dd422</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[16]/div[2]/div/div/div/div</value>
      <webElementGuid>ebfa06f2-1353-4d31-96bb-26075f85eac2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Итого' or . = 'Итого')]</value>
      <webElementGuid>4aef64fa-f0b1-40a0-ac61-73640320fc32</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
