<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_</name>
   <tag></tag>
   <elementGuidId>0a48e6c5-4e08-4ebb-8c29-48e484dbb4d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;button&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8ac18e72-9dd2-4772-88f7-ac79ac7afa16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary block full-width m-b</value>
      <webElementGuid>74bfae69-8e47-404a-ac9c-f1435eb52027</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e5d91d1f-b02f-4a23-81eb-e8123faea99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>login</value>
      <webElementGuid>e6f558a1-60bf-4bc4-83a6-1a95bcf756e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Вход</value>
      <webElementGuid>1db72be0-89e8-42b1-b1d4-7acac4068ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;gray-bg&quot;]/div[@class=&quot;container body-content&quot;]/div[@class=&quot;login-page&quot;]/div[@class=&quot;text-center animated center-container login-content fadeIn&quot;]/div[1]/form[1]/fieldset[1]/div[@class=&quot;form-group&quot;]/button[@class=&quot;btn btn-primary block full-width m-b&quot;]</value>
      <webElementGuid>12f6d13f-cabd-49f8-b0c2-a35df2d90ac4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='button']</value>
      <webElementGuid>38824363-222d-48c5-ba5b-707bb9cdb914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Вход']/parent::*</value>
      <webElementGuid>48245ef8-4682-47b1-bdae-dd58d677281d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>dcfa203c-4a60-47c2-9dde-92916ecb05b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@name = 'button' and (text() = 'Вход' or . = 'Вход')]</value>
      <webElementGuid>1ec65e07-86d0-460a-92ed-4e783afa7e6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
